### ISSUE TITLE
Obstacle Placement

### ISSUE THREAD

**Issue by DeanTuesday** [JakeDarling/magicflight#21] opened 2015-07-24 13:33 UTC
Need floating obstacles (blimps, other planes, kytes, birds), and need obstacles coming up from the ground (street lights, buildings, rocks, cliffs). Potentially falling obstacles (meteor, bomb, bird, space junk).
Obstacles must disappear with the world chunk.
Moving obstacles (bird, meteor) must disappear when off screen.

**Comment by JakeDarling** [comment] 2015-07-25 13:22
> Moving obstacles (bird, meteor) must disappear when off screen.

Why not just let them be covered by ```Obstacles must disappear with the world chunk.```

**Comment by JakeDarling** [comment] 2015-07-25 13:28
> Potentially falling obstacles (meteor, bomb, bird, space junk).

**Comment by DeanTuesday** [comment] 2015-07-31 20:34
They aren't going to be attached to a world chunk, but when they hit the edge of the entire world would be a good time to dispose of them

**Comment by JakeDarling** [comment] 2015-08-26 19:33
They already are attached to a chunk. No sense in double cleaning. Closing this as a dupe of #19

**Closed** 2015-08-26 19:33 UTC
